#!/bin/bash

# by default, tile all windows
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)

yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Software Update|Dictionary|VLC|System Preferences|^Calculator|^iTerm|^Karabiner-Elements|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# yabai -m config external_bar all:32:0
#borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

yabai -m config external_bar all:35:0 \
    window_border on \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement second_child \
    window_topmost off \
    window_shadow float \
    window_opacity off \
    window_opacity_duration 0.0 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.0 \
    window_border_width 2 \
    window_border_hidpi off \
    window_border_radius 11 \
    window_border_blur off \
    window_animation_duration 0 \
    active_window_border_color 0xffe1e3e4 \
    normal_window_border_color 0xff494d64 \
    insert_feedback_color 0xff9dd274 \
    split_ratio 0.50 \
    auto_balance off \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    \
    top_padding 1 \
    bottom_padding 0 \
    left_padding 0 \
    right_padding 0 \
    window_gap 6

## Sketchybar stuff
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"